### PR TITLE
New pull request

### PR DESCRIPTION
**Pull request by ekottifiok**
Added some files

### CODE REVIEW

**Comment by ekottifiok** [comment]
looks good to me

**Review by Lvhiz — COMMENTED** [review]
Dude these codes are overwhelming 😂

**Review by Lvhiz — APPROVED** [review]

**Review by Lvhiz — APPROVED** [review]

**Comment by ekottifiok** [comment]
thanks man I can now merge

**Comment by ekottifiok** [comment]
okay it has already merged thanks it was set on auto when reviewed

**Pull request merged**
